### ISSUE TITLE
Hard coded paths in bindata.go

### ISSUE THREAD

**Issue by scottjbarr** [achiku/dgw#2]
There are two hard coded paths in `bindata.go`

Example.

    path := "/Users/achiku/.go/1.6.1/src/github.com/achiku/dgw/template/struct.tmpl"

How about a command line argument that specifies the template directory?

**Comment by achiku** [comment]
Good catch. I will add `bindata.go` to .gitignore since the below line should generate it before compile. https://github.com/achiku/dgw/blob/master/dgw.go#L1

**Comment by scottjbarr** [comment]
Now when installing I see...

    $ go get -u github.com/achiku/dgw
    # github.com/achiku/dgw
    src/github.com/achiku/dgw/dgw.go:261: undefined: Asset

**Comment by achiku** [comment]
@scottjbarr Fixed!
